/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.int_watch.conf
 */
#ifndef DISCOVERYOBJECTS_H
#define DISCOVERYOBJECTS_H

/* function declarations */
void init_discoveryObjects(void);

#endif /* DISCOVERYOBJECTS_H */
