/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.int_watch.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "discoveryObjects.h"

/*
 * The variables we want to tie the relevant OIDs to.
 * The agent will handle all GET and (if applicable) SET requests
 * to these variables automatically, changing the values as needed.
 */

u_long    doConsultationTime = 0;  /* XXX: set default value */
u_long    doFoundDevices = 0;  /* XXX: set default value */
u_long    doNewFoundDevices = 0;  /* XXX: set default value */
in_addr_t    doDeviceAddress = 0;  /* XXX: set default value */
in_addr_t    doDeviceAddressMac = 0;  /* XXX: set default value */

/*
 * Our initialization routine, called automatically by the agent 
 * (Note that the function name must match init_FILENAME()) 
 */
void
init_discoveryObjects(void)
{
  netsnmp_handler_registration *reg;

    const oid doConsultationTime_oid[] = { 1,3,6,1,2,1,44523,1,1 };
  static netsnmp_watcher_info doConsultationTime_winfo;
    const oid doFoundDevices_oid[] = { 1,3,6,1,2,1,44523,1,2 };
  static netsnmp_watcher_info doFoundDevices_winfo;
    const oid doNewFoundDevices_oid[] = { 1,3,6,1,2,1,44523,1,3 };
  static netsnmp_watcher_info doNewFoundDevices_winfo;
    const oid doDeviceAddress_oid[] = { 1,3,6,1,2,1,44523,1,4 };
  static netsnmp_watcher_info doDeviceAddress_winfo;
    const oid doDeviceAddressMac_oid[] = { 1,3,6,1,2,1,44523,1,5 };
  static netsnmp_watcher_info doDeviceAddressMac_winfo;
  static netsnmp_watcher_info doDeviceAddressName_winfo;

  /*
   * a debugging statement.  Run the agent with -DdiscoveryObjects to see
   * the output of this debugging statement. 
   */
  DEBUGMSGTL(("discoveryObjects", "Initializing the discoveryObjects module\n"));


    /*
     * Register scalar watchers for each of the MIB objects.
     * The ASN type and RO/RW status are taken from the MIB definition,
     * but can be adjusted if needed.
     *
     * In most circumstances, the scalar watcher will handle all
     * of the necessary processing.  But the NULL parameter in the
     * netsnmp_create_handler_registration() call can be used to
     * supply a user-provided handler if necessary.
     *
     * This approach can also be used to handle Counter64, string-
     * and OID-based watched scalars (although variable-sized writeable
     * objects will need some more specialised initialisation).
     */
    DEBUGMSGTL(("discoveryObjects",
                "Initializing doConsultationTime scalar integer.  Default value = %d\n",
                doConsultationTime));
    reg = netsnmp_create_handler_registration(
             "doConsultationTime", NULL,
              doConsultationTime_oid, OID_LENGTH(doConsultationTime_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&doConsultationTime_winfo, &doConsultationTime, sizeof(u_long),
			      ASN_COUNTER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &doConsultationTime_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched doConsultationTime" );
    }

    DEBUGMSGTL(("discoveryObjects",
                "Initializing doFoundDevices scalar integer.  Default value = %d\n",
                doFoundDevices));
    reg = netsnmp_create_handler_registration(
             "doFoundDevices", NULL,
              doFoundDevices_oid, OID_LENGTH(doFoundDevices_oid),
              HANDLER_CAN_RONLY);
    netsnmp_init_watcher_info(&doFoundDevices_winfo, &doFoundDevices, sizeof(u_long),
			      ASN_COUNTER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &doFoundDevices_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched doFoundDevices" );
    }

    DEBUGMSGTL(("discoveryObjects",
                "Initializing doNewFoundDevices scalar integer.  Default value = %d\n",
                doNewFoundDevices));
    reg = netsnmp_create_handler_registration(
             "doNewFoundDevices", NULL,
              doNewFoundDevices_oid, OID_LENGTH(doNewFoundDevices_oid),
              HANDLER_CAN_RONLY);
    netsnmp_init_watcher_info(&doNewFoundDevices_winfo, &doNewFoundDevices, sizeof(u_long),
			      ASN_COUNTER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &doNewFoundDevices_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched doNewFoundDevices" );
    }

    DEBUGMSGTL(("discoveryObjects",
                "Initializing doDeviceAddress scalar integer.  Default value = %d\n",
                doDeviceAddress));
    reg = netsnmp_create_handler_registration(
             "doDeviceAddress", NULL,
              doDeviceAddress_oid, OID_LENGTH(doDeviceAddress_oid),
              HANDLER_CAN_RONLY);
    netsnmp_init_watcher_info(&doDeviceAddress_winfo, &doDeviceAddress, sizeof(in_addr_t),
			      ASN_IPADDRESS, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &doDeviceAddress_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched doDeviceAddress" );
    }

    DEBUGMSGTL(("discoveryObjects",
                "Initializing doDeviceAddressMac scalar integer.  Default value = %d\n",
                doDeviceAddressMac));
    reg = netsnmp_create_handler_registration(
             "doDeviceAddressMac", NULL,
              doDeviceAddressMac_oid, OID_LENGTH(doDeviceAddressMac_oid),
              HANDLER_CAN_RONLY);
    netsnmp_init_watcher_info(&doDeviceAddressMac_winfo, &doDeviceAddressMac, sizeof(in_addr_t),
			      ASN_IPADDRESS, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &doDeviceAddressMac_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched doDeviceAddressMac" );
    }


  DEBUGMSGTL(("discoveryObjects",
              "Done initalizing discoveryObjects module\n"));
}
